Iss35 feeding mechanic
excaliburHisSheath/hangry-river-horse pull request #39
Opened 2017-06-23 18:46 UTC by excaliburHisSheath

I've added the basic feeding mechanic described in #35:

- Players start with 10 balls in their food pile.
- A player's hippo eats a ball from their food pile every 0.75 seconds.
- Each ball their hippo eats gives the player 1 point.
- If the hippo tries to eat and there are no balls, the player loses and is removed from the game and the host screen.

This provides a baseline auto-removal mechanism to the game, which should fix our issues with overcrowded screens. More work needs to be done for #35, but this is working well enough to deploy it while we add more functionality.

2017-06-23 19:20 UTC, wufire commented on src/api.rs
> +    let player = Player {
Hello player object. I did not expect to so you so soon

2017-06-23 19:25 UTC, excaliburHisSheath commented on src/api.rs
> +    let player = Player {
Oh yeah, I forgot to mention that I removed all the separate maps for scoreboard and usernames and such. They were making the code harder to work with and were a speculative optimization that we probably don't need yet in practice. So I've unified everything into `Player` for now, and we can split things back out if accessing the player map becomes a bottleneck.

2017-06-23 20:25 UTC, wufire requested changes

2017-06-23 20:25 UTC, wufire commented on src/api.rs
> +        let mut players = players.write().expect("Players were poisoned");
The players were poisoned with cyanide.

2017-06-23 20:25 UTC, wufire commented on src/api.rs
> +        let mut players = players.write().expect("Players were poisoned");
Haha, so a review is much more serious than a `comment`. Neat!

2017-06-23 20:25 UTC, wufire commented on src/api.rs
> -        *score
In the old version here, what did the `*` do?

2017-06-23 20:25 UTC, wufire commented on src/api.rs
> -        *score
I know I could just look that up, but now it's part of a code review.

2017-06-23 20:25 UTC, wufire commented on src/api.rs
> +    let players = players.read().expect("Player map was poisoned!");
Why were we `lock`ing before and now we are `read`ing?

2017-06-23 20:25 UTC, wufire commented on src/game.rs
> +                    // Otherwise, the hippo is le dead.
☠️

2017-06-23 20:25 UTC, wufire commented on www/host.js
> +        switch (hippo.side.side) {
`side.side`?

2017-06-23 20:29 UTC, wufire commented on src/api.rs
> +    let player = Player {
I think this is the correct path for now. Easier to think of conceptually, too.

2017-06-23 20:29 UTC, wufire approved these changes

2017-06-23 20:34 UTC, excaliburHisSheath commented on src/api.rs
> -        *score
So `score` as a `&usize`, meaning a pointer to a `usize`. To change the `usize` that it points to, you have to dereference the pointer, which is what `*` does. If you didn't have the `*`, then Rust would think you're trying to change the pointer itself.

2017-06-23 20:36 UTC, excaliburHisSheath commented on src/api.rs
> +    let players = players.read().expect("Player map was poisoned!");
Before we were using a `Mutex`, now we're using `RwLock`. Mutex ensures that only one thread can access the data, and that thread always has mutable access once it has acquired the lock. `RwLock` has both `read()` method, which allows multiple threads to read the data at the same time, and a `write()` method, which behaves the same as `lock()` did.

Switching to `RwLock` give us a little bit of leeway to have multiple threads access the data in parallel if they don't need to mutate it.

2017-06-23 20:37 UTC, excaliburHisSheath commented on www/host.js
> +        switch (hippo.side.side) {
`hippo.side` is an object: `{ side: number, array: Hippo[] }`. That could be renamed to `hippo.side.sideId` or something to make it clearer.

2017-06-23 20:37 UTC, merged

2017-06-24 04:06 UTC, wufire commented on src/api.rs
> -        *score
Ooo, does rust allow you to manipulate the pointers directly?

2017-06-24 04:07 UTC, wufire commented on src/api.rs
> +    let players = players.read().expect("Player map was poisoned!");
Ah, yeah. I remember talking about this, now.

2017-06-24 04:39 UTC, excaliburHisSheath commented on src/api.rs
> -        *score
Yuppers. Rust is a lot like C/C++ in that most of the fundamental parts of the language are very thin abstractions over how the hardware works. Within an `unsafe` block, you can manipulate raw memory in the same way you would C/C++. Normally, though, Rust restricts you to only performing safe operations, even though you're always working with pointers when you use reference/borrows.

In Rust terms, though, `&usize` is a "reference to a `usize`" or "a `usize` borrow". Under the hood it's still functionally a pointer, hence why you need to manually dereference it, but Rust also "raw pointers", which allow you to do all the unsafe pointer hackery you can do in C/C++.

2017-06-24 04:44 UTC, wufire commented on src/api.rs
> -        *score
Ooo, a `safe`/`unsafe` mode is a good idea. Allows both the dangerous superpowers and the reasonable limitations.

2017-06-24 05:01 UTC, excaliburHisSheath commented
Fun fact: C# also has an `unsafe` block that let's you handle raw pointers.

On Fri, Jun 23, 2017, 11:44 PM wufire <notifications@github.com> wrote:

> *@wufire* commented on this pull request.
> ------------------------------
>
> In src/api.rs
> <https://github.com/excaliburHisSheath/hangry-river-horse/pull/39#discussion_r123870456>
> :
>
> >
>          // Get the player's current score, or return an `InvalidPlayer` error if it's not in
>          // the scoreboard.
> -        let score = scoreboard
> -            .get_mut(&player_id)
> -            .ok_or(Error::InvalidPlayer(player_id))?;
> -        *score += 1;
> -        *score
>
> Ooo, a safe/unsafe mode is a good idea. Allows both the dangerous
> superpowers and the reasonable limitations.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/excaliburHisSheath/hangry-river-horse/pull/39#discussion_r123870456>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AB0BHY6jHN4_cK5Yvv6DW9zvVPLWLcPmks5sHJQjgaJpZM4OD6mM>
> .
>